### ISSUE TITLE
Cryptococcus NTR: Haploid fruiting phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#111] opened 2016-05-25 13:40 UTC
NTR
1)  Haploid fruiting phenotype

   xref: GO:0000905 " sporocarp development involved in asexual reproduction"

2)  Presence of haploid fruiting (is_a haploid fruiting phenotype)
3)  absence of haploid fruiting (is_a haploid fruiting phenotype)
4)  altered haploid fruiting (is_a haploid fruiting phenotype)
5)  increased haploid fruiting (is_a altered haploid fruiting)
6)  decreased haploid fruiting(is_a altered haploid fruiting)
7)  increased rate of haploid fruiting (is_a altered haploid fruiting)
8)  decreased rate of haploid fruiting(is_a altered haploid fruiting)

**Comment by dianeoinglis** [comment] 2016-08-02 19:40
'Haploid fruiting, also referred to as "monokaryotic fruiting" in Cryptococcus involves the formation of a "fruit body." or "fruiting body." This term is used for fungi, bacteria and slime molds but the structures in these 3 groups are not equivalent. When identical terms are used differently by disparate research communities, a means of distinguishing among these species is important. The term "haploid fruiting body formation" is the term that I am most concerned about. One possible solution is to prepend the terms the way some GO terms are constructed...for example, the terms "cell wall" and "fungal-type cell wall" are used. This is one example of a conflictling term but others may be encountered. The use of the "species-type" has precedence in the GO and is straightforward.

Here are some descriptions for each type of fruiting body. 
Fruiting body (fungi), a multicellular structure on which spore-producing structures, such as basidia or asci, are born.
Fruiting body (bacteria), the aggregation of myxobacterial cells when nutrients are scarce (not to be confused with those in fungi)
Fruiting body (slime mold), the sorophore and sorus of a slime mold (not to be confused with sporocarp, a multicellular structure on which spore-producing structures are borne

My request is for the fungal terms only. The myxobacterial and slime mold terms are for comparison only.

Possible 'formation' terms, 
1) "fungal-type fruiting body formation"
2) "myxobacterial-type fruiting body formation"
3) "slime mold-type fruiting body formation" OR "slime mold-type multicellular fruiting body formation"

Possible process terms, only the fungal term is requested:
1) "fungal-type haploid fruiting" with synonym "monokaryotic fruiting"
2) "myxobacterial-type fruiting"
3) "slime mold-type fruiting"

Please consider this issue and comment. Deciding on a general strategy for resolving term collisions will minimize this problem when it arises.

Thank you,
Diane

**Comment by dsiegele** [comment] 2016-08-10 16:35
Since 'fruiting body' is used in so many different ways, I suggest that we use 'fruiting body phenotype' as the overall umbrella term for the node and then have branches for distinct types of fruiting bodies, such as 'sporocarp (fungi)' for fungal fruiting bodies. See example:

fruiting body phenotype
.....fruiting body formation phenotype
..........sporocarp (fungi) formation phenotype
..........sporocarp (fungi) morphology phenotype

Question: I'm not sure what the distinction is between fruiting body formation and fruiting? Is one to indicate the presence/absence of fruiting bodies and other phenotypes affecting the structure? and fruiting would be for phenotypes that affect the process of fruiting? For other structures, we've used 'morphology' to cover the former and 'formation' to cover the latter.

Debby

**Comment by dianeoinglis** [comment] 2016-08-12 17:28
Hi Debby, 

The Basidiomycete "sporocarp" is called a "basidiocarp" and is a sexual structure. Haploid fruiting in Cryptococcus is an asexual process that occurs in the absence of a mating partner and is specifically referred to as "haploid" or "monokaryotic" fruiting to distinguish it from the sexual (dikaryotic) fruiting process. Haploid fruiting does not occur in all fungi and their are other subtle differences between mating (fruiting) and haploid fruiting in Cryptococcus. “Fused clamps” are formed between 2 clamp cells during mating and “unfused clamps” are seen during haploid fruiting.

The NTR for fruiting body formation is #110. 

Terms for "haploid fruiting" phenotype and "haploid fruiting body formation" phenotype are both needed. The "haploid fruiting body" is the spore-bearing structure that forms during the process of "haploid fruiting." The fruiting process can be impaired without affecting "haploid fruit body formation" such as when no spores form on the fruit body or if the spores that form are inviable. For an "abolished haploid fruiting body formation" phenotype, haploid fruiting would have to be initiated and a change in the number of shape of the fruiting bodies would be observed. If the haploid fruiting process was absent or impaired prior to the stage when haploid fruiting bodies form, the appropriate term would be "haploid fruiting phenotype."

Let me know if this term request needs further clarification.

Thank you!
Diane

**Comment by dianeoinglis** [comment] 2016-08-31 14:36
This term request is for the process of haploid (monokaryotic) fruiting and is distinct from haploid fruiting body formation. 

haploid fruiting
synonym: monokaryotic fruiting
Def: A developmental process of asexual reproduction that is similar to fruiting during sexual reproduction but is the result of mating between strains of the same mating-type or self-mating under conditions of nutrient deprivation.

NTR's:
haploid fruiting phenotype
altered haploid fruiting phenotype
increased haploid fruiting phenotype
decreased haploid fruiting phenotype
abolished haploid fruiting phenotype

Thank you,
Diane

**Comment by dsiegele** [comment] 2017-05-29 21:56
Please review the terms I made for haploid fruiting. 

 +[Term]
+id: OMP:0007542
 +name: haploid fruiting phenotype
 +def: "An asexual reproduction phenotype where progeny are contained in a fruiting body that forms as the result of mating between strains of the same mating-type or self-mating." [OMP:DAS]
 
  +[Term]
+id: OMP:0007543
 +name: presence of haploid fruiting
 +def: "A haploid fruiting phenotype where a microbe can reproduce by the process of haploid fruiting." [OMP:DAS]
 +synonym: "presence of monokaryotic fruiting" EXACT []
 +is_a: OMP:0007542 ! haploid fruiting phenotype

 +[Term]
 +id: OMP:0007544
 +name: absence of haploid fruiting
 +def: "A haploid fruiting phenotype where a microbe is unable to reproduce by the process of haploid fruiting." [OMP:DAS]
 +synonym: "absence of monokaryotic fruiting" EXACT []
 +is_a: OMP:0007542 ! haploid fruiting phenotype
 
 +[Term]
 +id: OMP:0007545
 +name: altered  haploid fruiting
 +def: "A haploid fruiting phenotype where the rate, frequency, timing, or extent of the process of haploid fruiting is altered relative to a designated control." [OMP:DAS]
 +synonym: "altered monokaryotic fruiting" EXACT []
 +is_a: OMP:0007144 ! altered asexual reproduction
 +is_a: OMP:0007542 ! haploid fruiting phenotype

 +[Term]
 +id: OMP:0007546
 +name: increased haploid fruiting
 +def: "An altered haploid fruiting phenotype where the rate, frequency, timing, or extent of the process of haploid fruiting is increased relative to a designated control." [OMP:DAS]
 +synonym: "increased monokaryotic fruiting" RELATED []  <-- this was changed to EXACT
 +is_a: OMP:0007545 ! altered  haploid fruiting

 +[Term]
 +id: OMP:0007547
 +name: decreased haploid fruiting
 +def: "An altered haploid fruiting phenotype where the rate, frequency, timing, or extent of the process of haploid fruiting is decreased relative to a designated control." [OMP:DAS]
 +synonym: "decreased monokaryotic fruiting" EXACT []
 +is_a: OMP:0007545 ! altered  haploid fruiting

 +[Term]
 +id: OMP:0007548
 +name: abolished haploid fruiting
 +def: "A decreased fruiting phenotype where the process of haploid fruiting is abolished." []
 +synonym: "abolished monokaryotic fruiting" EXACT []
 +is_a: OMP:0007544 ! absence of haploid fruiting
 +is_a: OMP:0007547 ! decreased haploid fruiting

**Comment by dianeoinglis** [comment] 2017-06-10 19:29
These terms and defs look good. Would one use 'altered haploid fruiting phenotype' if the morphology of the haploid fruiting bodies were abnormal? If so, could that be mentioned in the def?
Thanks!

**Comment by dsiegele** [comment] 2017-06-15 21:22
I think there should be a set of terms for fruiting body morphology. I would start at the top with a very general definition for fruiting body morphology and then can add terms for haploid fruiting body morphology and diploid fruiting body morphology. What do you think?

**Closed** 2019-07-02 06:44 UTC
Labels: new term request, term(s) made
